RAYLIB ?= ./external/raylib-5.5/src/
CFLAGS = -m64 -std=c99 -pedantic -Wall -Wshadow -Wpointer-arith -Wcast-qual

all: test_umls test_umla test_parser



test_umls: src/test_umls.c
	gcc src/test_umls.c -I src/ -o tests/test_umls
	./tests/test_umls
test_umla: src/test_umla.c
	gcc src/test_umla.c -I src/ -o tests/test_umla
	./tests/test_umla
test_parser: src/test_parser.c
	gcc src/test_parser.c -O0 -I $(RAYLIB) -L $(RAYLIB) -lraylib -lGL -lm -lpthread -ldl -lrt -lX11 -o tests/test_parser 
	./tests/test_parser
